"""Phase 3: Proactive Watchdog Layer - Automated Monitoring and Notifications"""

import logging
from datetime import datetime, timedelta
from typing import Any, Callable, Dict, List, Optional

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
from pydantic import BaseModel, Field
from sqlalchemy import Column, DateTime, Integer, JSON, String, create_engine, func, text
from sqlalchemy.orm import Session, declarative_base

logger = logging.getLogger(__name__)

Base = declarative_base()


class NotificationType(BaseModel):
    """Notification types for the watchdog."""
    id: str
    title: str
    description: str
    severity: str  # 'critical', 'warning', 'info'


class SystemNotification(BaseModel):
    """A system notification generated by the watchdog."""
    notification_id: str = Field(..., description="Unique notification ID")
    type: str = Field(..., description="Notification type")
    severity: str = Field(..., description="Severity level")
    title: str = Field(..., description="Notification title")
    message: str = Field(..., description="Detailed message")
    related_entity: Optional[str] = Field(default=None, description="Related entity (e.g., transfer_id)")
    created_at: datetime = Field(..., description="Creation timestamp")
    read: bool = Field(default=False, description="Whether notification has been read")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class WatchdogTrigger(BaseModel):
    """Definition of a monitoring trigger."""
    trigger_id: str = Field(..., description="Unique trigger ID")
    name: str = Field(..., description="Trigger name")
    condition: str = Field(..., description="Condition to monitor")
    threshold: Optional[float] = Field(default=None, description="Threshold value")
    active: bool = Field(default=True, description="Whether trigger is active")


class ProactiveWatchdog:
    """
    Proactive Watchdog Layer for Autonomous Agent
    
    Monitors:
    - Upcoming ET transfers (< 24h)
    - Low confidence predictions (< 85%)
    - Missing required data
    - System health metrics
    """
    
    def __init__(
        self,
        database_url: str,
        check_interval_minutes: int = 60,
        confidence_threshold: float = 0.85,
        et_warning_hours: int = 24
    ):
        """
        Initialize the Proactive Watchdog.
        
        Args:
            database_url: PostgreSQL connection string
            check_interval_minutes: How often to run checks
            confidence_threshold: Minimum acceptable confidence
            et_warning_hours: Hours before ET to generate warning
        """
        self.database_url = database_url
        self.check_interval_minutes = check_interval_minutes
        self.confidence_threshold = confidence_threshold
        self.et_warning_hours = et_warning_hours
        
        self.engine = create_engine(database_url)
        
        # Initialize scheduler
        self.scheduler = BackgroundScheduler()
        self.triggers: List[WatchdogTrigger] = []
        self.notification_callbacks: List[Callable] = []
        
        self._initialize_triggers()
        
        logger.info("Proactive Watchdog initialized")
    
    def _initialize_triggers(self):
        """Initialize default monitoring triggers."""
        self.triggers = [
            WatchdogTrigger(
                trigger_id="upcoming_et_24h",
                name="Upcoming ET Records (< 24h)",
                condition="et_date >= NOW() AND et_date <= NOW() + INTERVAL '24 hours'",
                threshold=None,
                active=True
            ),
            WatchdogTrigger(
                trigger_id="low_confidence",
                name="Low Confidence Predictions",
                condition="confidence_lower < threshold",
                threshold=self.confidence_threshold,
                active=True
            ),
            WatchdogTrigger(
                trigger_id="missing_et_data",
                name="Missing ET Data",
                condition="recipient_id IS NULL OR embryo_id IS NULL",
                threshold=None,
                active=True
            ),
            WatchdogTrigger(
                trigger_id="system_health",
                name="System Health Check",
                condition="monitoring_enabled = true",
                threshold=None,
                active=True
            ),
        ]
    
    def register_notification_callback(self, callback: Callable):
        """Register a callback to be called when notifications are generated."""
        self.notification_callbacks.append(callback)
    
    def start_monitoring(self):
        """Start the background monitoring scheduler."""
        if self.scheduler.running:
            logger.warning("Scheduler already running")
            return
        
        # Schedule the monitoring task
        self.scheduler.add_job(
            self.run_health_check,
            IntervalTrigger(minutes=self.check_interval_minutes),
            id="watchdog_health_check",
            name="Watchdog Health Check"
        )
        
        self.scheduler.start()
        logger.info(f"Watchdog monitoring started (interval: {self.check_interval_minutes}min)")
    
    def stop_monitoring(self):
        """Stop the background monitoring scheduler."""
        if self.scheduler.running:
            self.scheduler.shutdown()
            logger.info("Watchdog monitoring stopped")
    
    async def run_health_check(self):
        """Execute all monitoring checks."""
        try:
            logger.info("Running watchdog health check...")
            
            notifications = []
            
            # Check 1: Upcoming ET transfers
            et_warnings = await self._check_upcoming_et_transfers()
            notifications.extend(et_warnings)
            
            # Check 2: Low confidence predictions
            confidence_warnings = await self._check_low_confidence_predictions()
            notifications.extend(confidence_warnings)
            
            # Check 3: Missing data
            data_warnings = await self._check_missing_data()
            notifications.extend(data_warnings)
            
            # Dispatch notifications
            for notification in notifications:
                await self._dispatch_notification(notification)
            
            logger.info(f"Health check complete. Generated {len(notifications)} notifications.")
            
        except Exception as e:
            logger.error(f"Health check failed: {str(e)}")
    
    async def _check_upcoming_et_transfers(self) -> List[SystemNotification]:
        """Check for ET transfers happening within the warning window."""
        notifications = []
        
        try:
            with Session(self.engine) as session:
                query = text(
                    """
                    SELECT
                        transfer_id,
                        et_number,
                        et_date,
                        farm_location
                    FROM et_transfers
                    WHERE et_date >= CURRENT_DATE
                      AND et_date <= CURRENT_DATE + (:warning_hours * INTERVAL '1 hour')
                      AND et_date > CURRENT_DATE
                    ORDER BY et_date ASC;
                    """
                )

                result = session.execute(query, {"warning_hours": self.et_warning_hours})
                rows = result.fetchall()
                
                if rows:
                    logger.info(f"Found {len(rows)} upcoming ET transfers")
                    
                    for row in rows:
                        hours_until = (row[2] - datetime.now()).total_seconds() / 3600
                        
                        notification = SystemNotification(
                            notification_id=f"upcoming_et_{row[0]}",
                            type="upcoming_et",
                            severity="warning" if hours_until < 12 else "info",
                            title=f"Upcoming ET Transfer: ET #{row[1]}",
                            message=f"ET transfer scheduled in {hours_until:.1f} hours at {row[3]}. "
                                   f"Ensure all required data and equipment are ready.",
                            related_entity=f"transfer_{row[0]}",
                            created_at=datetime.now(),
                            metadata={
                                "transfer_id": row[0],
                                "et_number": row[1],
                                "et_date": str(row[2]),
                                "hours_until": hours_until
                            }
                        )
                        notifications.append(notification)
                
        except Exception as e:
            logger.error(f"Failed to check upcoming ET transfers: {str(e)}")
        
        return notifications
    
    async def _check_low_confidence_predictions(self) -> List[SystemNotification]:
        """Check for predictions with low confidence scores."""
        notifications = []
        
        try:
            with Session(self.engine) as session:
                query = text(
                    """
                    SELECT
                        p.prediction_id,
                        p.transfer_id,
                        p.model_name,
                        p.probability,
                        p.confidence_lower,
                        p.predicted_at
                    FROM predictions p
                    WHERE p.confidence_lower < :threshold
                      AND p.predicted_at >= NOW() - INTERVAL '24 hours'
                    ORDER BY p.confidence_lower ASC;
                    """
                )

                result = session.execute(query, {"threshold": self.confidence_threshold})
                rows = result.fetchall()
                
                if rows:
                    logger.info(f"Found {len(rows)} low-confidence predictions")
                    
                    for row in rows:
                        confidence_percent = float(row[4]) * 100 if row[4] else 0
                        
                        notification = SystemNotification(
                            notification_id=f"low_confidence_{row[0]}",
                            type="low_confidence",
                            severity="warning",
                            title=f"Low Confidence Alert: {row[2]}",
                            message=f"Model {row[2]} for transfer #{row[1]} has low confidence ({confidence_percent:.1f}%). "
                                   f"Recommendation: Review input data quality and consider re-analysis.",
                            related_entity=f"prediction_{row[0]}",
                            created_at=datetime.now(),
                            metadata={
                                "prediction_id": row[0],
                                "transfer_id": row[1],
                                "model_name": row[2],
                                "confidence": float(row[4]) if row[4] else 0
                            }
                        )
                        notifications.append(notification)
                
        except Exception as e:
            logger.error(f"Failed to check low-confidence predictions: {str(e)}")
        
        return notifications
    
    async def _check_missing_data(self) -> List[SystemNotification]:
        """Check for transfers with missing required data."""
        notifications = []
        
        try:
            with Session(self.engine) as session:
                query = """
                SELECT 
                    transfer_id,
                    et_number,
                    recipient_id,
                    embryo_id,
                    protocol_id
                FROM et_transfers
                WHERE et_date >= CURRENT_DATE 
                  AND et_date <= CURRENT_DATE + INTERVAL '7 days'
                  AND (recipient_id IS NULL OR embryo_id IS NULL OR protocol_id IS NULL)
                ORDER BY et_date ASC;
                """
                
                result = session.execute(text(query))
                rows = result.fetchall()
                
                if rows:
                    logger.info(f"Found {len(rows)} transfers with missing data")
                    
                    for row in rows:
                        missing_fields = []
                        if row[2] is None:
                            missing_fields.append("recipient")
                        if row[3] is None:
                            missing_fields.append("embryo")
                        if row[4] is None:
                            missing_fields.append("protocol")
                        
                        notification = SystemNotification(
                            notification_id=f"missing_data_{row[0]}",
                            type="missing_data",
                            severity="critical",
                            title=f"Missing Data: ET #{row[1]}",
                            message=f"Transfer #{row[0]} is missing: {', '.join(missing_fields)}. "
                                   f"Complete the data entry before the scheduled transfer date.",
                            related_entity=f"transfer_{row[0]}",
                            created_at=datetime.now(),
                            metadata={
                                "transfer_id": row[0],
                                "missing_fields": missing_fields
                            }
                        )
                        notifications.append(notification)
                
        except Exception as e:
            logger.error(f"Failed to check missing data: {str(e)}")
        
        return notifications
    
    async def _dispatch_notification(self, notification: SystemNotification):
        """Dispatch notification to all registered callbacks."""
        try:
            for callback in self.notification_callbacks:
                await callback(notification) if hasattr(callback, "__await__") else callback(notification)
            
            # Store notification in database (optional)
            logger.info(f"Notification dispatched: {notification.notification_id}")
            
        except Exception as e:
            logger.error(f"Failed to dispatch notification: {str(e)}")
